### ISSUE TITLE
Releasing ImageNet weights ?

### ISSUE THREAD

**Issue by rohit-gupta** [LiheYoung/ShrinkMatch#1]
Hi,

Thank you for releasing the code for this state of the art method. I am working on a comparative study across various Semi-Supervised learning methods, for which purpose availability of pre-trained ImageNet models for your method would ensure best possible evaluation. 

Would it be possible for you to release your ImageNet models ? 

Thanks.

**Comment by LiheYoung** [comment]
Hi, the model weights of our ShrinkMatch on ImageNet are provided here: 
- [ImageNet-1%labels-top1acc-67.5](https://drive.google.com/file/d/1WU0EeLTlClF17NYzWJW8sh9H6Bj16a0U/view?usp=sharing)
- [ImageNet-10%labels-top1acc-74.5](https://drive.google.com/file/d/1ry8Epnnum7x6kY1AetQ7jpC_ZLDJR4rm/view?usp=sharing)
